In [1]:
%matplotlib inline
import numpy as np

## 情境 -- 倒水問題
##### Ｑuestion：
> 有分別裝有 a 公升與 b 公升水的甲, 乙兩支瓶子  
每一輪操作都是先將甲瓶的水倒出一半到乙瓶, 然後再將乙瓶的水倒出一半回甲瓶
1. 寫出此倒水問題的轉移矩陣 A
2. 若a = 0.6, b = 0.4, 一輪後﹑二輪後及三輪後的水量分布矩陣 X1, X2, X3 分別為何﹖


##### Answer：
>`甲瓶`﹕留在甲瓶的水加上從乙瓶倒過來的水  
$0.5*a + 0.5*(0.5*a + b) = 0.75a + 0.5b$  

>`乙瓶`﹕從甲瓶倒過來的水加上本身之水後的一半  
$0.5*(0.5*a + b) = 0.25a + 0.5b$

> 轉移矩陣A為：

In [2]:
A = np.array([[0.75, 0.5 ],
              [0.25, 0.5 ]])

In [3]:
A

array([[0.75, 0.5 ],
       [0.25, 0.5 ]])

> X1, X2, X3分別為：

In [4]:
X1 = A @ np.array([0.6, 0.4])

In [5]:
X1

array([0.65, 0.35])

In [6]:
X2 = A @ X1

In [7]:
X2

array([0.6625, 0.3375])

In [8]:
X3 = A @ X2

In [9]:
X3

array([0.665625, 0.334375])