In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

### 1. `numpy array` 純量乘法

In [2]:
x = np.array([1, 2, 3])

In [3]:
3*x

array([3, 6, 9])

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
3*A

array([[ 3,  6,  9],
       [12, 15, 18]])

### 2. 向量加法

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [9]:
x + y

array([5, 7, 9])

### 3.內積是矩陣乘法的核心
內積在numpy指令式 `np.dot` ,因為太常用,所以也可以用 `@`

In [10]:
np.dot(x, y)

32

In [11]:
x@y

32

In [12]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
B = np.array([[0, 2],
              [1, -2],
              [0, 1]])

In [15]:
A@B

array([[2, 1],
       [5, 4]])

In [16]:
B@A

array([[ 8, 10, 12],
       [-7, -8, -9],
       [ 4,  5,  6]])

### 4.Identity Matrix $In$
快速造出 $n*n$ 的Identity Matrix

In [17]:
I3 = np.eye(3)

In [18]:
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
A@I3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
B

array([[ 0,  2],
       [ 1, -2],
       [ 0,  1]])

In [23]:
I3@B

array([[ 0.,  2.],
       [ 1., -2.],
       [ 0.,  1.]])

### 5.反矩陣 `np.linalg.inv(A)`

In [25]:
A = np.array([[1, 2, 1],
              [4, 4, 5], 
              [6, 6, 7]])

In [26]:
B = np.linalg.inv(A)

In [27]:
B

array([[-1. , -4. ,  3. ],
       [ 1. ,  0.5, -0.5],
       [ 0. ,  3. , -2. ]])

In [28]:
C = A@B

In [29]:
C

array([[ 1.00000000e+00, -8.88178420e-16,  4.44089210e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.77635684e-15],
       [ 0.00000000e+00, -1.77635684e-15,  1.00000000e+00]])

檢驗兩個矩陣是否相近 `np.allclose(A, B)`

In [31]:
np.allclose(C, np.eye(3))

True

四捨五入 `round()`

In [33]:
u = np.array([-1.5, -0.5, 0.5, 1.5, 2.5, 3.5])

In [35]:
u.round()

array([-2., -0.,  0.,  2.,  2.,  4.])

In [37]:
B.round() + 0

array([[-1., -4.,  3.],
       [ 1.,  0.,  0.],
       [ 0.,  3., -2.]])

In [40]:
C.round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [39]:
C.round() + 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])